import { StyleSheet } from 'react-native';
import {
  Color,
  Border,
  FontSize,
  FontFamily,
  Padding,
  Gap,
} from '../../../GlobalStyles';

export const styles = StyleSheet.create({
  logoIcon: {
    width: '100%',
    height: '100%',
    borderRadius: Border.br_5xs,
  },
  logoWrapper: {
    backgroundColor: Color.colorLightHover,
    width: 80,
    maxHeight: 94,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Border.br_5xs,
    marginBottom: Padding.p_5xs,
  },
  storeName: {
    fontSize: FontSize.size_sm,
    lineHeight: 14,
    fontWeight: '600',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorBlack,
    textAlign: 'left',
    height: 32,
  },
  offerCategory: {
    fontSize: FontSize.size_4xs,
    lineHeight: 12,
    fontWeight: '600',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorBlack,
    textAlign: 'left',
  },
  allTypeOf: {
    fontSize: FontSize.size_2xs,
    letterSpacing: 1,
    lineHeight: 12,
    fontWeight: 'bold',
    fontFamily: FontFamily.poppinsBold,
    color: Color.colorOrangered_100,
    textAlign: 'left',
    alignSelf: 'stretch',
    paddingTop: Padding.p_11xs,
  },
  offParent: {
    flex: 1,
    gap: Gap.gap_2xs,
    alignSelf: 'stretch',
    marginTop: -4,
  },
  frameParent: {
    flexDirection: 'row',
    gap: Gap.gap_md,
    alignSelf: 'stretch',
  },
  frameWrapper: {
    borderStyle: 'solid',
    borderColor: Color.colorGainsboro_100,
    borderWidth: 1,
    width: 240,
    minHeight: 110,
    overflow: 'hidden',
    paddingHorizontal: Padding.p_5xs,
    paddingTop: Padding.p_5xs,
    borderRadius: Border.br_5xs,
  },
  couponCode: {
    fontSize: FontSize.size_3xs,
    lineHeight: 12,
    fontWeight: 'bold',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorOrangered_100,
    textAlign: 'center',
    padding: 1,
    borderRadius: 6,
    marginTop: 4,
    backgroundColor: Color.colorOrangered_200,
  },
  expiredView: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  expired: {
    fontSize: FontSize.size_3xs,
    lineHeight: 12,
    fontWeight: '500',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorDarkGray,
    textAlign: 'left',
    maxWidth: 80,
  },
  expiryDate: {
    fontSize: FontSize.size_3xs,
    lineHeight: 12,
    fontWeight: '500',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorDarkGray,
    textAlign: 'right',
  },
  gdOfferText: {
    fontSize: FontSize.size_2xs,
    lineHeight: 12,
    fontWeight: 'bold',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorBrown,
    textAlign: 'left',
    fontStyle: 'italic',
    paddingBottom: Padding.p_7xs,
  },
  originalPriceView: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: Gap.gap_sm,
    paddingTop: Padding.p_11xs,
  },
  originalPrice: {
    fontSize: FontSize.size_xs,
    lineHeight: 12,
    fontWeight: 'bold',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorGray400,
    textAlign: 'left',
    textDecorationLine: 'line-through',
  },
  offerPrice: {
    fontSize: FontSize.size_xs,
    lineHeight: 12,
    fontWeight: 'bold',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorOrangered_100,
    textAlign: 'right',
  },
});
