import { StyleSheet } from 'react-native';
import {
  Border,
  FontFamily,
  Color,
  FontSize,
  Gap,
  Padding,
} from '../../../GlobalStyles';
import { screenWidth } from '../../helper/Utils';

export const styles = StyleSheet.create({
  wrapperLayout: {
    borderTopLeftRadius: Border.br_5xs,
    borderTopRightRadius: Border.br_5xs,
    marginTop: -1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  framePosition: {
    left: 5,
    position: 'absolute',
  },
  offTypo: {
    fontFamily: FontFamily.poppinsBold,
    fontWeight: '700',
    textAlign: 'left',
    textTransform: 'uppercase',
    position: 'absolute',
  },
  offerImage: {
    height: 108,
    width: screenWidth * 0.365 - 2,
    borderTopLeftRadius: Border.br_5xs,
    borderTopRightRadius: Border.br_5xs,
    marginTop: 1,
  },
  offerImageWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: screenWidth * 0.365,
  },
  frameWrapper: {
    backgroundColor: Color.colorMistyrose,
    height: 110,
    justifyContent: 'space-between',
    zIndex: 0,
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  frameChild: {
    top: 29,
    width: 5,
    height: 3,
  },
  frameItem: {
    top: -0,
    width: 61,
    height: 29,
  },
  upto: {
    top: 3,
    fontWeight: 'bold',
    fontFamily: FontFamily.poppinsMedium,
    textAlign: 'left',
    textTransform: 'uppercase',
    color: Color.colorWhite,
    lineHeight: 11,
    fontSize: FontSize.size_3xs,
    left: 12,
    position: 'absolute',
  },
  text: {
    top: 14,
    color: Color.colorGold,
    lineHeight: 12,
    fontWeight: 'bold',
    fontSize: FontSize.size_3xs,
    left: 12,
  },
  off: {
    top: 8,
    left: 40,
    fontSize: FontSize.size_4xs,
    transform: [
      {
        rotate: '90deg',
      },
    ],
    color: Color.colorWhite,
    lineHeight: 10,
    fontWeight: 'bold',
  },
  vectorParent: {
    top: 4,
    left: -10,
    width: 64,
    zIndex: 1,
    height: 32,
    position: 'absolute',
  },
  titleText: {
    fontSize: FontSize.size_2xs,
    fontFamily: FontFamily.poppinsBold,
    fontWeight: 'bold',
    color: Color.colorBlack,
    lineHeight: 12,
    alignSelf: 'stretch',
  },
  titleWrapper: {
    backgroundColor: Color.colorWhite,
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingStart: Padding.p_7xs,
  },
  frameParent: {
    maxWidth: screenWidth * 0.365,
    width: '100%',
    gap: Gap.gap_lg,
    justifyContent: 'space-between',
  },
  innerWrapper: {
    borderRadius: Border.br_5xs,
    height: 180,
    borderColor: Color.colorOrangered_100,
    borderWidth: 0.2,
    display: 'flex',
    flexDirection: 'column',
    gap: Gap.gap_xs,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  gdDiscountContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    height: 16,
    width: '100%',
  },
  gdImage: {
    height: 16,
    width: '100%',
  },
  gdText: {
    position: 'absolute',
    fontSize: 8,
    fontFamily: FontFamily.poppinsBold,
    fontWeight: 'bold',
    color: Color.colorWhite,
    left: 4,
    top: 2,
  },
  subCategoryName: {
    fontSize: FontSize.size_5xs,
    fontFamily: FontFamily.poppinsRegular,
    color: Color.colorBlack,
    textAlign: 'left',
    lineHeight: 12,
    alignSelf: 'stretch',
    paddingStart: Padding.p_7xs,
  },
  expiryDate: {
    fontSize: FontSize.size_5xs,
    fontFamily: FontFamily.poppinsRegular,
    color: Color.colorBlack,
    textAlign: 'center',
    lineHeight: 12,
    alignSelf: 'stretch',
  },
  expiredContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: Padding.p_7xs,
  },
  button: {
    borderRadius: Border.br_3xs,
    backgroundColor: Color.colorOrangered_100,
    width: '90%',
    marginHorizontal: Padding.p_7xs,
    alignItems: 'center',
  },
  couponText: {
    fontSize: FontSize.size_5xs,
    fontFamily: FontFamily.poppinsBold,
    color: Color.colorWhite,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 12,
    alignSelf: 'stretch',
    paddingVertical: 1,
  },
});
