import { StyleSheet } from "react-native";
import {
  Padding,
  Gap,
  Color,
  Border,
  FontFamily,
  FontSize,
} from "../../../GlobalStyles";

export const styles = StyleSheet.create({
  midRowSpaceBlock: {
    paddingVertical: 0,
    paddingHorizontal: Padding.p_3xs,
  },
  frameParentFlexBox: {
    gap: Gap.gap_lg,
    flex: 1,
  },
  frameWrapperBg: {
    backgroundColor: Color.colorMistyrose,
    padding: Padding.p_9xs,
    alignItems: "center",
  },
  wrapperLayout: {
    borderRadius: Border.br_5xs,
    justifyContent: "center",
  },
  frameViewPosition: {
    borderBottomLeftRadius: Border.br_9xs,
    borderBottomRightRadius: Border.br_9xs,
    justifyContent: "center",
    backgroundColor: Color.colorWhite,
  },
  sortByWrapperLayout: {
    height: 18,
    borderRadius: Border.br_9xs,
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "solid",
    flexDirection: "row",
    alignItems: "center",
  },
  filterTypo: {
    textAlign: "left",
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
    fontSize: FontSize.size_3xs,
  },
  frameFlexBox: {
    alignContent: "flex-start",
    flexWrap: "wrap",
    flexDirection: "row",
    alignSelf: "stretch",
    marginBottom: 90,
  },
  subtractIcon: {
    width: 430,
    height: 54,
    display: "none",
  },
  bodyShotOfADarkSkinnedFaIcon: {
    width: 25,
    height: 40,
  },
  bodyShotOfADarkSkinnedFaWrapper: {
    width: 40,
    alignItems: "center",
  },
  frameWrapper: {
    borderRadius: Border.br_3xs,
    backgroundColor: Color.colorMistyrose,
  },
  all: {
    fontSize: FontSize.size_4xs,
    letterSpacing: 1,
    lineHeight: 9,
    fontFamily: FontFamily.poppinsRegular,
    textAlign: "center",
    color: Color.colorBlack,
    alignSelf: "stretch",
  },
  allWrapper: {
    width: 48,
    paddingHorizontal: 0,
    paddingVertical: Padding.p_11xs,
    justifyContent: "center",
    alignItems: "center",
  },
  frameContainer: {
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 6,
    elevation: 6,
    shadowOpacity: 1,
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: Color.colorOrangered_100,
    borderBottomLeftRadius: Border.br_9xs,
    borderBottomRightRadius: Border.br_9xs,
    borderTopRightRadius: Border.br_3xs,
    borderTopLeftRadius: Border.br_3xs,
    backgroundColor: Color.colorWhite,
  },
  frameView: {
    justifyContent: "center",
    borderTopRightRadius: Border.br_3xs,
    borderTopLeftRadius: Border.br_3xs,
    borderBottomRightRadius: Border.br_9xs,
  },
  frameWrapper2: {
    borderTopLeftRadius: Border.br_9xs,
    borderTopRightRadius: Border.br_9xs,
  },
  frameParent1: {
    justifyContent: "center",
  },
  frameGroup: {
    backgroundColor: "#f5f3f3",
    padding: Padding.p_9xs,
    borderRadius: Border.br_3xs,
    gap: Gap.gap_lg,
    alignSelf: "stretch",
  },
  image122Icon: {
    maxWidth: "100%",
    maxHeight: "100%",
    overflow: "hidden",
    alignSelf: "stretch",
    width: "100%",
    flex: 1,
  },
  image122Wrapper: {
    height: 120,
    overflow: "hidden",
    flexDirection: "row",
    alignSelf: "stretch",
    backgroundColor: Color.colorWhite,
    borderRadius: Border.br_5xs,
  },
  frameChild: {
    width: 8,
    height: 8,
  },
  ellipseParent: {
    backgroundColor: Color.colorOrangered_100,
    paddingHorizontal: Padding.p_5xs,
    marginTop: -4,
    borderRadius: Border.br_9xs,
    paddingVertical: Padding.p_11xs,
    flexDirection: "row",
    alignItems: "center",
    gap: Gap.gap_xs,
  },
  component2: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  component2Wrapper: {
    overflow: "hidden",
    flexDirection: "row",
    alignSelf: "stretch",
    backgroundColor: Color.colorWhite,
    borderRadius: Border.br_5xs,
  },
  filterSettingsSlidersIcon1: {
    width: 14,
    height: 14,
    overflow: "hidden",
  },
  filter: {
    color: Color.colorOrangered_100,
  },
  filterSettingsSlidersIcon1Parent: {
    paddingHorizontal: Padding.p_9xs,
    paddingVertical: Padding.p_11xs,
    borderColor: Color.colorOrangered_100,
    height: 18,
    gap: Gap.gap_xs,
  },
  sortBy: {
    color: Color.colorBlack,
  },
  sortByWrapper: {
    backgroundColor: Color.colorWhitesmoke_100,
    borderColor: Color.colorLightslategray,
    paddingVertical: 0,
    paddingHorizontal: Padding.p_3xs,
  },
  frameParent10: {
    flexDirection: "row",
    alignItems: "center",
  },
  frameWrapper10: {
    borderRadius: 6,
    backgroundColor: "#f5f5f5",
    padding: Padding.p_7xs,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
  },
  frameParent11: {
    gap: Gap.gap_xl,
  },
  frameWrapper12: {
    alignItems: "center",
    flex: 1,
  },
  frameParent9: {
    borderBottomRightRadius: Border.br_19xl,
    borderBottomLeftRadius: Border.br_19xl,
  },
  frameParent: {
    flexDirection: "row",
    alignSelf: "stretch",
  },
  midRowInner: {
    alignSelf: "stretch",
    flex: 1,
  },
  midRow: {
    alignItems: "center",
    alignSelf: "stretch",
    flex: 1,
  },
  listingPage: {
    height: 932,
    gap: Gap.gap_xs,
    width: "100%",
    flex: 1,
    backgroundColor: Color.colorWhite,
  },
});
