import { StyleSheet } from 'react-native';
import {
  FontFamily,
  Color,
  FontSize,
  Gap,
  Border,
  Padding,
} from '../../../GlobalStyles';

export const styles = StyleSheet.create({
  frameParent3: {
    display: 'flex',
  },
  frameWrapper: {
    borderStyle: 'solid',
    borderWidth: 1,
    width: 150,
    height: 224,
    borderColor: Color.colorGainsboro_300,
    borderRadius: Border.br_5xs,
  },
  frameParent: {
    flex: 1,
  },
  iconWrapper: {
    width: '100%',
    height: 130,
  },
  logoIcon: {
    width: '100%',
    height: '100%',
    borderRadius: Border.br_5xs,
    marginTop: -1,
  },
  gdDiscountContainer: {
    position: 'absolute',
    bottom: 6,
    left: 0,
    height: 16,
    width: '100%',
  },
  gdImage: {
    height: 16,
    width: '100%',
  },
  gdText: {
    position: 'absolute',
    fontSize: 8,
    fontFamily: FontFamily.poppinsBold,
    fontWeight: 'bold',
    color: Color.colorWhite,
    left: 4,
    top: 2,
  },
  offParent: {
    borderBottomRightRadius: Border.br_5xs,
    borderBottomLeftRadius: Border.br_5xs,
    backgroundColor: Color.colorWhite,
    borderStyle: 'dashed',
    borderRadius: 0.001,
    borderTopWidth: 0.5,
    gap: Gap.gap_2xs,
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    borderColor: Color.colorGainsboro_300,
  },
  storeName: {
    fontSize: FontSize.size_xs,
    lineHeight: 14,
    fontWeight: '600',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorBlack,
    textAlign: 'left',
    paddingTop: Padding.p_9xs,
    alignSelf: 'flex-start',
    paddingHorizontal: Padding.p_7xs,
    height: 32,
  },
  offerCategory: {
    fontSize: FontSize.size_5xs,
    lineHeight: 12,
    fontWeight: '600',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorDarkGray,
    textAlign: 'left',
    alignSelf: 'flex-start',
    paddingHorizontal: Padding.p_7xs,
  },
  couponCode: {
    display: 'flex',
    fontSize: FontSize.size_3xs,
    lineHeight: 12,
    fontWeight: 'bold',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorOrangered_100,
    textAlign: 'center',
    padding: 1,
    borderRadius: 6,
    marginTop: 4,
    backgroundColor: Color.colorOrangered_200,
    width: '90%',
    alignSelf: 'center',
  },
  expiredView: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
    width: '90%',
    alignSelf: 'center',
  },
  expired: {
    fontSize: FontSize.size_3xs,
    lineHeight: 12,
    fontWeight: '500',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorDarkGray,
    textAlign: 'left',
  },
  expiryDate: {
    fontSize: FontSize.size_3xs,
    lineHeight: 12,
    fontWeight: '500',
    fontFamily: FontFamily.poppinsSemiBold,
    color: Color.colorDarkGray,
    textAlign: 'right',
  },
  vectorParent: {
    top: 4,
    left: -10,
    width: 64,
    zIndex: 1,
    height: 32,
    position: 'absolute',
  },
  frameChildVector: {
    top: 29,
    width: 5,
    height: 3,
  },
  framePosition: {
    left: 5,
    position: 'absolute',
  },
  frameItem: {
    top: -0,
    width: 61,
    height: 29,
  },
  upto: {
    top: 3,
    fontWeight: '500',
    fontFamily: FontFamily.poppinsMedium,
    textAlign: 'left',
    textTransform: 'uppercase',
    color: Color.colorWhite,
    lineHeight: 11,
    fontSize: FontSize.size_3xs,
    left: 12,
    position: 'absolute',
  },
  text: {
    top: 14,
    color: Color.colorGold,
    lineHeight: 12,
    fontWeight: '700',
    fontSize: FontSize.size_3xs,
    left: 12,
  },
  off: {
    top: 8,
    left: 40,
    fontSize: FontSize.size_4xs,
    transform: [
      {
        rotate: '90deg',
      },
    ],
    color: Color.colorWhite,
    lineHeight: 10,
    fontWeight: '700',
  },
  offTypo: {
    fontFamily: FontFamily.poppinsBold,
    fontWeight: '700',
    textAlign: 'left',
    textTransform: 'uppercase',
    position: 'absolute',
  },
  frameIcon: {
    left: -8,
    zIndex: 1,
  },
  frameChild1: {
    left: 142,
    zIndex: 2,
  },
  frameLayout: {
    height: 16,
    width: 16,
    top: 124,
    position: 'absolute',
  },
});
